FROM node:18

WORKDIR /home/node/app

COPY package*.json ./

ARG API_URL
ARG SESSION_SECRET 
ARG SESSION_EXPIRY
ARG AWS_REGION
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_BUCKET_NAME

ENV API_URL=${API_URL}
ENV SESSION_SECRET=${SESSION_SECRET}
ENV SESSION_EXPIRY=${SESSION_EXPIRY}
ENV AWS_REGION=${AWS_REGION}
ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
ENV AWS_BUCKET_NAME=${AWS_BUCKET_NAME}

RUN npm i 

COPY . .

EXPOSE 3000

CMD [ "npm", "start" ]