name: pa11y tests

on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    name: Pa11y-ci tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Start server
        run: npm run start

      - name: Run pa11y-ci
        run: |
          npm run pa11y